resources:
  - name: node_app_jfrog
    type: gitRepo
    repoPath: skylark05/node_app_jfrog
    configuration:
      integrationName: skylar05_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline_1
    setup:
      runtime: host
    steps:
      - name: test_bash_step
        type: bash
        setup:
          runtime: 
            type: host
        triggeredBy:
          resources:
            - node_app_jfrog 
        execution:
          onExecute:
            - echo "First run....."
            - echo "executing step_A..."
